import { PDFDocument, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import fs from "fs";
import path from "path";
import { SKU_LABELS, formatVnd } from "./config";

/** Legal MVP clauses — exact wording from Legal/Product; do not paraphrase. */
export const LICENSE_CLAUSES = [
  "1. Credit: Buyer ghi credit producer đúng tên listing trên release công khai (trừ khi Exclusive thỏa thuận khác ghi trong PDF).",
  "2. No-resale: Cấm bán lại / chuyển nhượng / sublicense beat, stem, hoặc license; không claim ownership master hay publishing.",
  "3. Sample warrant: Producer xác nhận đã khai sample; Rap App không clear mẫu; rủi ro uncleared thuộc producer/buyer theo luật áp dụng.",
  "4. Exclusive: SKU Exclusive = độc quyền theo territory/term trên PDF; sau bán platform delist + khóa lease; conflict -> freeze + Legal review (SLA 24h).",
  "5. Scope lease: Chỉ quyền dùng theo SKU đã mua (commercial/non theo dòng SKU); không bao gồm stems trừ khi SKU ghi rõ.",
] as const;

function wrapText(text: string, font: { widthOfTextAtSize: (t: string, s: number) => number }, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(next, size) <= maxWidth) {
      line = next;
    } else {
      if (line) lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

export async function generateLicensePdf(opts: {
  licenseId: string;
  buyerName: string;
  buyerEmail: string;
  producerName: string;
  beatTitle: string;
  sku: string;
  amountVnd: number;
  sampleFlag: string;
  orderId: string;
  territory?: string;
  term?: string;
}): Promise<string> {
  const dir = path.join(process.cwd(), "storage", "licenses");
  fs.mkdirSync(dir, { recursive: true });
  const pdfPath = path.join(dir, `${opts.licenseId}.pdf`);

  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit);
  const fontBytes = fs.readFileSync(path.join(process.cwd(), "assets/fonts/NotoSans-Regular.ttf"));
  const font = await doc.embedFont(fontBytes, { subset: true });

  let page = doc.addPage([612, 792]);
  let y = 750;
  const maxWidth = 512;
  const left = 50;
  const bottom = 50;

  const ensureSpace = (need: number) => {
    if (y - need < bottom) {
      page = doc.addPage([612, 792]);
      y = 750;
    }
  };

  const drawLines = (text: string, size = 10, color = rgb(0.15, 0.15, 0.15), gap = 4) => {
    const lines = wrapText(text, font, size, maxWidth);
    for (const line of lines) {
      ensureSpace(size + gap);
      page.drawText(line, { x: left, y, size, font, color });
      y -= size + gap;
    }
  };

  drawLines("RAP APP — LICENSE CERTIFICATE", 16, rgb(0, 0, 0), 6);
  y -= 6;

  // Dynamic fields
  drawLines(`License ID: ${opts.licenseId}`);
  drawLines(`Order ID: ${opts.orderId}`);
  drawLines(`Timestamp: ${new Date().toISOString()}`);
  drawLines(`SKU: ${SKU_LABELS[opts.sku] || opts.sku}`);
  drawLines(`Buyer: ${opts.buyerName} <${opts.buyerEmail}>`);
  drawLines(`Producer: ${opts.producerName}`);
  drawLines(`Beat: ${opts.beatTitle}`);
  drawLines(`Amount paid: ${formatVnd(opts.amountVnd)}`);
  drawLines(`Sample declaration: ${opts.sampleFlag}`);
  drawLines(`Territory: ${opts.territory || "Worldwide (unless stated otherwise)"}`);
  drawLines(`Term: ${opts.term || (opts.sku === "exclusive" ? "Per Exclusive terms on this license" : "Per SKU lease terms")}`);
  y -= 8;

  if (opts.sampleFlag === "uncleared") {
    drawLines(
      "DISCLAIMER (uncleared): Beat có sample chưa clear — chỉ bán lease; không bán Exclusive. Watermark/disclaimer áp dụng theo policy MVP.",
      9,
      rgb(0.65, 0.35, 0.05),
      3,
    );
    y -= 6;
  }

  drawLines("TERMS (Legal MVP — fixed template)", 12, rgb(0, 0, 0), 6);
  y -= 4;
  for (const clause of LICENSE_CLAUSES) {
    drawLines(clause, 9, rgb(0.2, 0.2, 0.2), 3);
    y -= 6;
  }

  ensureSpace(20);
  page.drawText("Generated by Rap App MVP — VN beat marketplace ($0 template)", {
    x: left,
    y: 36,
    size: 8,
    font,
    color: rgb(0.45, 0.45, 0.45),
  });

  const bytes = await doc.save();
  fs.writeFileSync(pdfPath, bytes);
  return pdfPath;
}
