import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import fs from "fs";
import path from "path";
import { SKU_LABELS, formatVnd } from "./config";

export async function generateLicensePdf(opts: {
  licenseId: string;
  buyerName: string;
  buyerEmail: string;
  producerName: string;
  beatTitle: string;
  sku: string;
  amountVnd: number;
  sampleFlag: string;
  orderId: string;
}): Promise<string> {
  const dir = path.join(process.cwd(), "storage", "licenses");
  fs.mkdirSync(dir, { recursive: true });
  const pdfPath = path.join(dir, `${opts.licenseId}.pdf`);

  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  let y = 740;
  const draw = (text: string, size = 11, f = font, color = rgb(0.2, 0.2, 0.2)) => {
    page.drawText(text, { x: 50, y, size, font: f, color, maxWidth: 512 });
    y -= size + 8;
  };

  draw("RAP APP — LICENSE CERTIFICATE", 18, bold, rgb(0, 0, 0));
  y -= 8;
  draw(`License ID: ${opts.licenseId}`);
  draw(`Order ID: ${opts.orderId}`);
  draw(`Date: ${new Date().toISOString()}`);
  y -= 6;
  draw(`Beat: ${opts.beatTitle}`);
  draw(`Producer: ${opts.producerName}`);
  draw(`Licensee: ${opts.buyerName} <${opts.buyerEmail}>`);
  draw(`SKU: ${SKU_LABELS[opts.sku] || opts.sku}`);
  draw(`Amount paid: ${formatVnd(opts.amountVnd)}`);
  draw(`Sample clearance: ${opts.sampleFlag}`);
  y -= 6;

  if (opts.sampleFlag === "uncleared") {
    const note =
      "DISCLAIMER: Uncleared samples. Commercial release may need extra clearance. Exclusive not available. Rap App/producer disclaim sample claims.";
    page.drawText(note, { x: 50, y, size: 9, font, color: rgb(0.7, 0.35, 0.05), maxWidth: 512, lineHeight: 12 });
    y -= 48;
  }

  if (opts.sku === "lease") draw("Rights: Non-exclusive MP3 lease. Limited commercial use. Producer retains ownership.");
  else if (opts.sku === "wav") draw("Rights: Non-exclusive WAV + stems lease. Broader commercial use. Producer retains ownership.");
  else if (opts.sku === "exclusive") draw("Rights: Exclusive ownership transfer. Beat delisted. Unique sale.");

  page.drawText("Generated by Rap App MVP — VN beat marketplace", {
    x: 50,
    y: 40,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  const bytes = await doc.save();
  fs.writeFileSync(pdfPath, bytes);
  return pdfPath;
}
